# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "shoppad"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "shoppad"

dbt-cloud:
  project-id: 184721

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["custom_tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-start:
  - "{{ url_decode_udf() }}"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"
  pro_apps:
    - sms
    - email
    - custom
    - segment
    - hubspot
    - salesforce
    - twilio
    - odoo
    - recharge
    - recharge_legacy
    - api
    - webhook
    - json_webhook
    - quickbooks
    - gorgias
    - ftp
    - image
    - openai
    - chatgpt
    - shipstation
    - api
    - airtable
    - data
    - dalle
    - square
    - klaviyo
    - gorgias
    - webrequest

  puc_apps:
    - infiniteoptions
    - tracktor
    - googlesheets
    - recharge

  glue_apps:
    - transform
    - filter
    - loop
    - delay
    - logs
    - iterator

  etl_fields:
    [
      "__HEVO__DATABASE_NAME",
      "__HEVO__INGESTED_AT",
      "__HEVO__LOADED_AT",
      "__HEVO__MARKED_DELETED",
      "__HEVO_ID",
    ]
  start_date: "2018-01-01"
  zombie_store_shopify_plans: [frozen, fraudulent, paused, dormant, cancelled]

seeds:
  +schema: seed_data
  shoppad:
    custom_app_daily_revenues:
      +column_types:
        first_dt: DATE
        last_dt: DATE

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  shoppad:
    +persist_docs:
      relation: true
      columns: true
    +transient: true
    +materialized: table
    +dbt-osmosis: "_model.yml"

    generic:
      +schema: support

    mesa:
      marts:
        workflows:
          +unique_key: workflow_id
        shops:
          +cluster_by: ["date_trunc('day', first_installed_at_pt)"]
          +unique_key: shop_subdomain

      staging:
        +schema: support
        stg_workflows:
          +unique_key: workflow_id
        stg_shops:
          +cluster_by: ["date_trunc('day', first_installed_at_pt)"]
          +unique_key: shop_subdomain
