
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'shoppad'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'shoppad'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"

vars:
    "dbt_date:time_zone": "America/Los_Angeles"

seeds:
    +schema: seed_data

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
    shoppad:
        +transient: true
        +materialized: table
        # Config indicated by + and applies to all files under models/example/
        # example:
        #   +materialized: view
        mesa:
            mart:
                step_runs:
                    +cluster_by: ['shop_id', 'shop_subdomain']

                workflow_runs:
                    +cluster_by: ['shop_id', 'shop_subdomain', 'workflow_id']

                shops:
                    +cluster_by: ["date_trunc('day', first_installed_at)"]

            staging:
                +materialized: view
                +schema: staging

                stg_step_runs:
                    +materialized: incremental
                    # +cluster_by: ['workflow_run_id']
