# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: "shoppad"
version: "1.0.0"
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: "shoppad"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target" # directory which will store compiled SQL files
clean-targets: # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "America/Los_Angeles"
  pro_apps:
    - sms
    - email
    - custom
    - segment
    - hubspot
    - salesforce
    - twilio
    - odoo
    - recharge
    - recharge_legacy
    - api
    - webhook
    - json_webhook
    - quickbooks
    - gorgias
    - ftp
    - image
    - openai
    - chatgpt
    - shipstation
    - api
    - airtable
    - data
    - dalle
    - square
    - klaviyo
    - gorgias
    - webrequest

  puc_apps:
    - infiniteoptions
    - tracktor
    - googlesheets
    - recharge

  etl_fields:
    [
      "__HEVO__DATABASE_NAME",
      "__HEVO__INGESTED_AT",
      "__HEVO__LOADED_AT",
      "__HEVO__MARKED_DELETED",
      "__HEVO_ID",
    ]
  activation_workflow_run_count: 1
  start_date: "2018-01-01"
  ugly_segment_fields:
    [
      uuid_ts,
      context_library_name,
      context_library_version,
      event,
      event_text,
      sent_at,
      received_at,
      original_timestamp,
    ]
  zombie_store_shopify_plans: [frozen, fraudulent, paused, dormant, cancelled]

  segment_page_views_table: "{{ source('mesa_segment', 'pages') }}"
  segment_sessionization_trailing_window: 3

seeds:
  +schema: seed_data
  shoppad:
    custom_app_daily_revenues:
      +column_types:
        first_dt: DATE
        last_dt: DATE

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  shoppad:
    +persist_docs:
      relation: true
      columns: true
    +transient: true
    +materialized: table
    +dbt-osmosis: "_model.yml"
    # Config indicated by + and applies to all files under models/example/
    # example:
    #   +materialized: view

    generic:
      +schema: support
      staging:
        stg_shop_infos:
          # +materialized: incremental
          # +on_schema_change: "sync_all_columns"
          # +unique_key: shop_subdomain
    mesa:
      marts:
        step_runs:
          +on_schema_change: "sync_all_columns"
          +cluster_by: ["shop_subdomain"]
          +unique_key: step_run_id

        workflow_runs:
          +cluster_by: ["shop_subdomain", "workflow_id"]
          +unique_key: workflow_run_id

        workflows:
          +unique_key: workflow_id

        shops:
          +cluster_by: ["date_trunc('day', first_installed_at_pt)"]
          +unique_key: shop_subdomain

      intermediate:
        # +materialized: "{{ 'view' if target.name in ['prod', 'default'] else 'table' }}"
        +schema: support
        int_shop_calendar:
        int_step_runs:
          +materialized: incremental
          +on_schema_change: "sync_all_columns"
          +unique_key: step_run_id
          +cluster_by: ["workflow_run_id"]
        int_workflow_runs:
          +on_schema_change: "sync_all_columns"
          +unique_key: workflow_run_id
          +cluster_by: ["shop_subdomain"]
        int_shops:
          +cluster_by: ["date_trunc('day', first_installed_at_pt)"]
          +unique_key: shop_subdomain

      staging:
        # +materialized: "{{ 'view' if target.name in ['prod', 'default'] else 'table' }}"
        +schema: support
        stg_step_runs:
          +materialized: incremental
          +on_schema_change: "sync_all_columns"
          +unique_key: step_run_id
          +cluster_by: ["workflow_run_id"]
        stg_workflows:
          +unique_key: workflow_id
        stg_workflow_runs:
          +materialized: incremental
          +on_schema_change: "sync_all_columns"
          +unique_key: workflow_run_id
          +cluster_by: ["shop_subdomain"]
        stg_shops:
          +cluster_by: ["date_trunc('day', first_installed_at_pt)"]
          +unique_key: shop_subdomain

    mesa_segment:
      staging:
        +schema: support
      intermediate:
        +schema: support

    customer_io:
      staging:
        +schema: support

tests:
  shoppad:
    mesa:
      staging:
        enabled: true #"{{ target.name not in ['prod', 'default'] }}"
      intermediate:
        enabled: true #"{{ target.name not in ['prod', 'default'] }}"
