version: 2

sources:
  - name: mongo_sync
    description: imports of mongo db into snowflake json objects
    database: mongo
    schema: public
    loader: hevo
    loaded_at_field: __hevo__loaded_at::varchar::timestamp_ntz

    freshness:
      warn_after:
        count: 36
        period: hour
      error_after:
        count: 48
        period: hour

    quoting:
      database: false
      schema: false
      identifier: false

    tables:
      - name: workflows
        identifier: m3_mesa_automations
        description: individual workflow records with user-input name, description, starting time and more.

      - name: workflow_steps
        identifier: m3_mesa_triggers
        description: The individual steps of a workflow, including the step name, type, and the workflow it belongs to.

      - name: shops
        identifier: m3_mesa
        description: each installation record of a mesa merchant application install.

        columns:
          - name: _id
            description: unique identifier for the shop account.
            data_tests:
              - unique
              - not_null
          - name: _created_at
            description: The time the shop account was created by installing the app.
            data_tests:
              - not_null
          - name: uuid
            description: The shopify subdomain of the shop account.

      - name: mesa_charges
        identifier: m3_mesa_charges
        columns:
          - name: _id
            description: unique identifier for the charge.
            data_tests:
              - unique
              - not_null
          - name: created_at
            data_tests:
              - not_null
      - name: mesa_install_records
        identifier: m3_mesa_installs
      - name: blog_studio_shops
        identifier: m3_blogstudio
      - name: bouncer_shops
        identifier: m3_bouncer
      - name: coin_shops
        identifier: m3_coin
      - name: smile_shops
        identifier: m3_smile
      - name: kitkarts_shops
        identifier: m3_kitkarts
      - name: infinite_options_shops
        identifier: m3_customizery_shops
      - name: page_studio_shops
        identifier: m3_pagestudio
      - name: uploadery_shops
        identifier: m3_uploadery_shops
      - name: tracktor_shops
        identifier: m3_tracktor

  - name: economy_data
    description: Snowflake Marketplace economy data used for things like currency conversion rates.
    database: MONGO
    schema: PUBLIC
    loader: Snowflake

    quoting:
      database: false
      schema: false
      identifier: false

    tables:
      - name: currency_conversion_rates
        identifier: CYBERSYN_CURRENCY_CONVERSION_RATES

  - name: mesa_segment
    description: events and objects sent to snowflake via segment.com.
    database: mongo
    schema: getmesa
    loader: segment.com
    loaded_at_field: received_at

    freshness:
      warn_after:
        count: 12
        period: hour
      error_after:
        count: 24
        period: hour

    quoting:
      database: false
      schema: false
      identifier: false

    tables:
      - name: flow_events
        identifier: mesa_flow
        columns:
          - name: id
            description: unique identifier for the flow event.
      - name: workflow_events
        identifier: automation
        freshness: null
        columns:
          - name: id
            description: unique identifier for the workflow event.

  - name: php_segment
    description: identified users via the getmesa segment app.
    schema: php
    loader: segment.com
    loaded_at_field: received_at
    freshness:
      warn_after:
        count: 36
        period: hour
      error_after:
        count: 48
        period: hour
    tables:
      - name: users
        identifier: users
        columns:
          - name: id
            description: shop subdomain and unique identifier for the user.
          - name: uuid
          - name: apps_mesa_meta_activatedat_value
